# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Alexander Kucera"
tagline: ""
description: "Follow <a href=\"https://micro.blog/AlexKucera\">@AlexKucera on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/AlexKucera\">@AlexKucera on Micro.blog</a>."
baseurl: ""
url: "https://AlexKucera.micro.blog"
markdown: "kramdown"
username: "AlexKucera"
microblog_user: "AlexKucera"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Alexander Kucera"
name: "Alexander Kucera"
gravatar_hash: "e6fd216c7e03931033e7ab026e46f00b"
avatar: "https://micro.blog/AlexKucera/avatar.jpg"
full_name: "Alexander Kucera"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "239"
gems: ["jekyll-paginate"]
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Alexander Kucera"
podcast: false