# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
# - name: "[TITLE]"

# - title: "[TITLE]"
# - description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
# - base# - url: "[PATH]" # e.g. /manton or /az/azasdfasdf
# - url: "http://[HOSTNAME]" # the base hostname & protocol for your site
# - markdown: kramdown
# - user# - name: "[USERNAME]"

# Navigation
nav:
  - # - name:           "About"
    href:           "/about/"
  - # - name:           "RSS"
    href:           "/feed.xml"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "Alexander Kucera"
tagline: ""
description: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
credits: "Powered by <a href=\"http://micro.blog/\">Micro.blog</a>."
baseurl: ""
url: "http://AlexKucera.micro.blog"
markdown: "kramdown"
username: "AlexKucera"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Alexander Kucera"
name: "Alexander Kucera"
gravatar_hash: "e6fd216c7e03931033e7ab026e46f00b"
avatar: "http://www.gravatar.com/avatar/e6fd216c7e03931033e7ab026e46f00b?s=160"
full_name: "Alexander Kucera"
bio: ""
twitter_username: ""
github_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"